In [10]:
#Create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays
import numpy as np
a=np.array([7,8])
b=np.array([8,6])
print(np.greater_equal(a,b))
print(np.greater(a,b))
print(np.less_equal(a,b))
print(np.less(a,b))

[False  True]
[False  True]
[ True False]
[ True False]


In [15]:
#Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives
import numpy as np
a=np.zeros(10)
print(a)
a=np.ones(10)
print(a)
a=np.ones(10)*5
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [26]:
#Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array
import numpy as np
a=np.array([[1,8],[7,6]])
print(a)
print(np.sum(a))
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))


[[1 8]
 [7 6]]
22
[ 8 14]
[ 9 13]


In [36]:
#Write a NumPy program to add, subtract, multiply, divide arguments element-wise
import numpy as np
print(np.add(8,9))
print(np.subtract(15,3))
print(np.multiply(15,3))
print(np.divide(15,3))


17
12
45
5.0


In [37]:
#Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in degree.
import numpy as np
print("sin: array of angles given in degrees")
print(np.sin(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))
print("cos: array of angles given in degrees")
print(np.cos(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))
print("tan: array of angles given in degrees")
print(np.tan(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))

sin: array of angles given in degrees
[0.         0.5        0.70710678 0.8660254  1.        ]
cos: array of angles given in degrees
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
tan: array of angles given in degrees
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [50]:
#Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the index label

import pandas as pd
dict_sr={'Id':([1,2,3]),'S.No':[111,112,113]}
label=['a','b','c']
df5=pd.DataFrame(dict_sr,index=label)
print(df5)

   Id  S.No
a   1   111
b   2   112
c   3   113


In [79]:
#Write a Pandas program to join the two given dataframes along rows and assign all data
import pandas as pd
dict_sr=pd.DataFrame({'Id':([1,2,3]),'S.No':[111,112,113]})
dict_sr1=pd.DataFrame({'Id':([4,5,6]),'S.No':[114,115,116]})

df6=pd.concat([dict_sr,dict_sr1])
print(df6)

   Id  S.No
0   1   111
1   2   112
2   3   113
0   4   114
1   5   115
2   6   116


In [80]:
#Write a Pandas program to detect missing values of a given DataFrame. Display True or False.
import pandas as pd
dict_sr=pd.DataFrame({'Id':([1,2,3]),'S.No':[111,112,np.nan]})
dict_sr1=pd.DataFrame({'Id':([4,5,6]),'S.No':[114,115,116]})

df6=pd.concat([dict_sr,dict_sr1])

print(df6.isna())

      Id   S.No
0  False  False
1  False  False
2  False   True
0  False  False
1  False  False
2  False  False


In [77]:
#Write a Pandas program to create and display a one-dimensional array-like object containing an array of data
import pandas as pd
ds = pd.Series([4,5,6])
print(ds)

0    4
1    5
2    6
dtype: int64
